# Generated by Django 4.0.2 on 2022-03-25 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymproapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=20)),
                ('Last_Name', models.CharField(max_length=20)),
                ('Contact', models.CharField(max_length=20)),
                ('Email_Id', models.CharField(max_length=50)),
                ('Age', models.CharField(max_length=20)),
                ('Describe', models.TextField()),
            ],
        ),
    ]
