# Generated by Django 4.0.2 on 2022-03-25 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gymproapp', '0002_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='Describe',
        ),
    ]
